"use string";

let ROOTDemoFinal = [
  "ROOT",
  "FNchangeName",
  Nikolai,
  "FNchangeBackgroundImage",
  NikolaiHome,
  "FNputSprait",
  [Himicy, 50, 30, 0], ///size //top //left
  "Это все механики, которые пока доступны",
  "Подробности ищи в <u>DemoRoots.js</u>",
  "Там можно ознакомиться с этой тестовой новеллой",
  "Спасибо за внимание!",
  "END",
];

let rootDemoSquare = [
  "FNchangeName",
  thoughts,
  "...",
  "~Я заметил в углу Лену, как обычно читавшую книгу~",
  "FNputSprait",
  [sprait, 30, 0, 50], ///size //top //left,
  "FNchangeName",
  nameLena,
  "Привет Семён",
  "Разве ты не должен сейчас помогать Ольге Дмитриевне в столовой?",
  "FNchangeName",
  autor,
  "И так далее...",
  ROOTDemoFinal,
];

let rootDemoScena = [
  "FNchangeBackgroundImage",
  sceneFon,
  "...",
  "К моему удивлению, я обнаружил Лену, тренирующую тенисные подачи",
  "FNchangeName",
  nameLena,
  "FNputSprait",
  [lenaSport, 15, 30, 50], ///size //top //left
  "Ой, привет. А ты наверное Алису ищешь?",
  "FNchangeName",
  you,
  "Да нет, просто решил прогуляться",
  "FNchangeName",
  thoughts,
  "~Я не стал уточнять у неё, почему она выбрала сцену, в качестве места для занятия тенисом~",
  "FNchangeName",
  autor,
  "И так далее...",
  ROOTDemoFinal,
];

let rootDemoStart = [
  "FNchangeBackgroundImage",
  fon1,
  "FNchangeName",
  you,
  "Демо показ движка",
  "Дабы измежать багов, лучше смотреть на пк или ноутбуке...",
  "Или на телефоне с горизонтально повёрнутым экраном",
  "Весь текст плавно появляется, пародируя печатную машинку",
  "В будущем будет способ изменить скорость появления текста",
  "Сейчас вы видети один фон, через клик будет другой",
  "FNchangeBackgroundImage",
  fon,
  "...",
  "Справа на панеле есть значёк глаза, с помощью него можно посмотреть фон полностью",
  "Рядом с ним значёк сохранения. Пока в разработке",
  "Как и в html тут можно использовать теги для показа текста <b>жирным</b>, <i>курсивным</i>, <s>перечёркнутым</s> и так далее",
  "Сейчас сменю имя",
  "FNchangeName",
  Slavya,
  "Теперь добавим спрайт Слави",
  "FNputSprait",
  [Slavya_spait1, 30, 0, 50], ///size //top //left
  "Привет, ты тут новенький?",
  "Сейчас подвину спрайт влево и приближу его",
  "FNdeleteSprait",
  Slavya_spait1,
  "FNputSprait",
  [Slavya_spait1, 40, 0, 30], ///size //top //left
  "Теперь поменяем эмоцию",
  "FNdeleteSprait",
  Slavya_spait1,
  "FNputSprait",
  [Slavya_spait2, 40, 0, 30], ///size //top //left
  "Теперь поиграемся с музыкой",
  "Сейчас начнется песня",
  "FNmusic",
  music2,
  "...",
  "Через клик песня перестанет играть",
  "FNmusic",
  stop,
  "...",
  "Так-же можно вставлять звуковые эффекты. Например как этот",
  "FNsound",
  sound1,
  "Шелест травы",
  "Звуковые эффекты также можно останавливать",
  "FNdeleteSprait",
  Slavya_spait2,
  "...",
  "FNchangeName",
  you,
  "Теперь перейдем к выборам действий",
  "FNchangeBackgroundImage",
  fon2,
  "Сейчас будет выбор, который по сути ничего не несёт, кроме лишней графомании",
  "FNdoChoice",
  "Съесть яблоко",
  [
    "MINI",
    "Была не была",
    "Обед всё равно ещё придётся подождать",
    "FNsound",
    applebite,
  ],
  "Не есть",
  "Да в принципе и не голодный я",
  "...",
  "FNchangeBackgroundImage",
  sqfon,
  "Теперь второй тип выбора",
  "Когда при выборе меняется ход повествования",
  "FNdoChoice",
  "Пойти на сцену",
  rootDemoScena,
  "Остаться на площади",
  rootDemoSquare,
  "Этот текст уже никто не прочитает (кроме вас - кодеров)",
];
